### ISSUE TITLE
Инициализация проекта

### ISSUE THREAD

**Issue by sh-ad** [moevm/MSE-2023-core-english-23#1]

**Comment by sh-ad** [comment]
выаыва

**Comment by sh-ad** [comment]
Комментарий два

**Comment by sh-ad** [comment]
Шаги задачи

**Comment by dvur0g** [comment]
Создать проект через https://start.spring.io/

Добавить в зависимости H2, Spring Data, Lombok, Spring Web.

Запушить в репозиторий.

**Comment by dvur0g** [comment]
Assignee: Павел
