### ISSUE TITLE
Аналитика статистики для Учителя

### ISSUE THREAD

**Issue by ilya201232** [moevm/MSE-2023-core-english-23#137]
Посмотреть варианты просмотра статистики по выбранному ученику в выбранный промежуток времени по оценкам, посещениям, темам, комментариям.

Посмотреть возможность выгрузки такой инфы в pdf.

**Comment by ilya201232** [comment]
![Image](https://github.com/moevm/MSE-2023-core-english-23/assets/44816360/bddf8345-1dfd-46e7-8310-0b5e7279e0d6)



![Image](https://github.com/moevm/MSE-2023-core-english-23/assets/44816360/3b9e0523-37f4-4c58-9ea7-ef5a879fa7ab)



![Image](https://github.com/moevm/MSE-2023-core-english-23/assets/44816360/3a526201-5974-43e5-85e1-9b161a428a4c)



![Image](https://github.com/moevm/MSE-2023-core-english-23/assets/44816360/5f6e80bb-f971-4223-8cf8-469ef5cd108e)

**Comment by dvur0g** [comment]
2) Можно тоже пока сделать круговую диаграмму.

3) Пока от выгрузки статистики в чат телеграмм отказываемся, работаем только с pdf.

4) Выгрузку комментариев пока не делаем.
