### ISSUE TITLE
Добавить возможность отмечать ДЗ как сделанные

### ISSUE THREAD

**Issue by dvur0g** [moevm/MSE-2023-core-english-23#143]
Нужен новый статус для ДЗ "сделанное/несделанное"
По умолчанию ДЗ несдержанное

Добавить кнопку у ИДЗ для перевода несделанного ИДЗ в статус сделанное, а сделанного ИДЗ в статус несделанное. Думаю, стоит сделать для этого одну кнопку типа toggle.

**Comment by ilya201232** [comment]
Возможный дупликат с #123
