### ISSUE TITLE
Проработать меню телеграм бота

### ISSUE THREAD

**Issue by dvur0g** [moevm/MSE-2023-core-english-23#2]
Assignee: Ксения

**Comment by dvur0g** [comment]
Assignee: Ксения

**Comment by dvur0g** [comment]
Разработать в любом графическом виде (н-р, Paint) первый вариант-макет меню бота, основываясь на двух сторях отсюда: https://miro.com/app/board/uXjVPjJmIO4=/

**Comment by velonzy** [comment]
Макет первого варианта меню телеграм-бота: https://t.me/test_english_velonzy_bot
