### ISSUE TITLE
Создать тестового бота

### ISSUE THREAD

**Issue by dvur0g** [moevm/MSE-2023-core-english-23#4]
Assignee: Илья

**Comment by dvur0g** [comment]
Создать бота, на котором начнётся разработка.

Инструкция: https://sendpulse.com/ru/knowledge-base/chatbot/telegram/create-telegram-chatbot

Внимание! Сделать всё до пункта "Как подключить бота в Sendpulse"

К Sendpulse его подключать не надо.

**Comment by ilya201232** [comment]
Telegram бот создан. 
Имя бота: Core English Test Bot
Username бота: core_english_test_bot
Ссылка: t.me/core_english_test_bot
