### ISSUE TITLE
Проработать варианты реализации создания Подписки средствами телеграм меню

### ISSUE THREAD

**Issue by dvur0g** [moevm/MSE-2023-core-english-23#52]
Необоходимо рассмотреть варианты, и выбрать формат, позволяющие работать с командами, требующими ввода данных от пользователя на примере создания Подписки.

При создании подписки необходимо получать от пользователя кол-во уроков в Подписке и начальную/конечную дату Подписки.

**Comment by ilya201232** [comment]
Простой запрос в гугле дает вот это: 
https://stackoverflow.com/questions/68142791/how-to-get-several-inputs-in-one-command-in-telegram-bot-api

К сожалению это все встроенные решения в библиотеке на python. Тем не менее из прочтенного видно, что реализация предложенных методов сводится к хранению для каждого пользователя сессионых данных.

**Comment by ilya201232** [comment]
Некоторые данные можно вводить через inline keyboard. Пример с выбором даты: https://pypi.org/project/python-telegram-bot-calendar.
Также, используя inline keyboard, можно менять текст сообщения и саму inline keyboard через callback механизм. Т.е. на каждой кнопке в клавиатуре хранится какая-то информация в формате String. При нажатии на эту кнопку формируется новый Update с CallbackQuery. Этот параметр уже в свою очередь будет хранить в себе данные из кнопки + объект сообщения, как при обычном сообщении. При этом параметр Message не будет присутствовать в Update. 

Ссылки на telegram api:
- Изменение сообщения: https://core.telegram.org/bots/api#updating-messages

**Comment by dvur0g** [comment]
Пока решили с Александром хранить кеш каждого пользователя в Caffeine
