### ISSUE TITLE
Реализовать логику отмены Подписки Учителем

### ISSUE THREAD

**Issue by dvur0g** [moevm/MSE-2023-core-english-23#61]
По нажатию на "Подробнее" под Подпиской из списка Подписок дать возможность отменить эту Подписку, показав кнопку "Отменить подписку". Также выставить корректные статусы Урокам в этой подписке.

**Comment by ilya201232** [comment]
Решили поместить эту кнопку рядом с кнопкой "Подробнее"

**Comment by ilya201232** [comment]
Также добавлю кнопку "Назад" для меню "Подробнее", чтобы можно было вернутся в начало
