### ISSUE TITLE
рефакторинг сервисного слоя

### ISSUE THREAD

**Issue by PashaThrowsException78** [moevm/MSE-2023-core-english-23#67]
1) унифицировать апи сервисов. какие-то сервисы принимают Update, какие-то DTO-шки -- это плохо.

пусть лучше все принимают дтошки, сервисы вообще по-хорошему не должны знать что такое телеграмовский Update

2) добавить недостающие аннотации @Transactional

**Comment by ilya201232** [comment]
По мимо выше перечисленного также требуется убедиться что:
- Методы save() стоят только где создаются новые объекты БД
- Не нужно делать так, чтобы на один сервис был лишь один репозиторий
