### ISSUE TITLE
Аналитика разграничения обязанностей ролей

### ISSUE THREAD

**Issue by dvur0g** [moevm/MSE-2023-core-english-23#79]
Здесь будет описание действий каждой роли

**Comment by ilya201232** [comment]
![Image](https://user-images.githubusercontent.com/44816360/227740429-984a8766-dc0b-4749-bbcd-9f11079f0468.png)



![Image](https://user-images.githubusercontent.com/44816360/227740433-950c2917-07ba-4044-b7ad-ad7e60da6c3e.png)



![Image](https://user-images.githubusercontent.com/44816360/227740444-9425bf56-3c7b-47f7-8ebd-5dd7d26c7dbf.png)



![Image](https://user-images.githubusercontent.com/44816360/227740450-66d2c45e-3ac2-457b-8a3c-f24e8515cd28.png)
