### ISSUE TITLE
При старте бота в сообщении приветствия (до нажаться кнопки /start) выводить текст

### ISSUE THREAD

**Issue by dvur0g** [moevm/MSE-2023-core-english-23#97]
Текст: "Нажимая кнопку старт, вы соглашаетесь с условиями оферты".

**Comment by ilya201232** [comment]
https://sendpulse.com/knowledge-base/chatbot/telegram/description

**Comment by dvur0g** [comment]
Пока заказчик дал только .doc файл с офертой, думаю, надо залить его на Гугл диск и ссылку на него (только для чтения)  сократить с помощью, например, https://vk.com/cc, и получившуюся ссылку предоставлять в дескрипшене. Сам файл договора прикрепляю в следующем комментарии здесь к задаче.

**Comment by dvur0g** [comment]
[Договор.docx](https://github.com/moevm/MSE-2023-core-english-23/files/11242824/default.docx)
